<a href="https://colab.research.google.com/github/nnknishant/nnknishant/blob/main/Numpy-Intro-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
n =  np.array([2,3,4,5,6])
n

array([2, 3, 4, 5, 6])

In [6]:
n[0], n[3]

(2, 5)

In [7]:
n[3],n[4],n[1]

(5, 6, 3)

In [8]:
n[-1],n[0]

(6, 2)

In [10]:
n[3], n[3]

(5, 5)

In [11]:
n[0:]

array([2, 3, 4, 5, 6])

In [12]:
n

array([2, 3, 4, 5, 6])

In [13]:
n[1:]

array([3, 4, 5, 6])

In [14]:
n[2:]

array([4, 5, 6])

In [15]:
n

array([2, 3, 4, 5, 6])

In [16]:
n[-0:]

array([2, 3, 4, 5, 6])

In [17]:
n[-1:]

array([6])

In [19]:
n[-1:],n[-2:],n[-3:]

(array([6]), array([5, 6]), array([4, 5, 6]))

In [20]:
n

array([2, 3, 4, 5, 6])

In [21]:
n[3:]

array([5, 6])

In [22]:
n[-3:]

array([4, 5, 6])

In [23]:
n[-3:],n[-4:]

(array([4, 5, 6]), array([3, 4, 5, 6]))

In [24]:
n[1:3]

array([3, 4])

In [25]:
n[2:3]

array([4])

In [26]:
n[2:4]

array([4, 5])

In [27]:
n[3:-1]

array([5])

In [28]:
n

array([2, 3, 4, 5, 6])

In [29]:
n[1:-2]

array([3, 4])

In [30]:
n[1:-3]

array([3])

In [31]:
a=np.array([2,3,4,.9,.8])
a

In [32]:
a

array([2. , 3. , 4. , 0.9, 0.8])

In [34]:
a[[1,2,3]]

array([3. , 4. , 0.9])

In [37]:
a[[0,-2,3]]

array([2. , 0.9, 0.9])

In [38]:
a[[0,-1,-2]]

array([2. , 0.8, 0.9])

In [39]:
a

array([2. , 3. , 4. , 0.9, 0.8])

In [40]:
n

array([2, 3, 4, 5, 6])

In [41]:
n.dtype

dtype('int64')

In [42]:
a.dtype

dtype('float64')

In [43]:
a*n

array([ 4. ,  9. , 16. ,  4.5,  4.8])

In [44]:
a+n

array([4. , 6. , 8. , 5.9, 6.8])

In [45]:
a-n

array([ 0. ,  0. ,  0. , -4.1, -5.2])

In [46]:
a/n

array([1.        , 1.        , 1.        , 0.18      , 0.13333333])

In [47]:
n[2],n[3]

(4, 5)

In [48]:
a[2],a[-2],a[3]

(4.0, 0.9, 0.9)

In [49]:
n[1:]

array([3, 4, 5, 6])

In [50]:
n[-1]

6

In [51]:
n[-1:]

array([6])

In [52]:
n[:-2]

array([2, 3, 4])

In [53]:
n[:-3]

array([2, 3])

In [55]:
#multidimensional array in numpy
m=np.array([
    [2,3,4],
   [4,5,6]
   ])

m

array([[2, 3, 4],
       [4, 5, 6]])

In [56]:
m.dtype

dtype('int64')

In [57]:
m.shape
#for show the number of column and rows

(2, 3)